### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by caijinyuan123** [12sdj/Random-Number-Generator#10]
希望能设置一个亲民的版本，不用太多复杂的设置，希望能将随机数库加强

**Comment by 12sdj** [comment]
你需要提供更多信息。
您所说的“亲民”指的是哪些方面？程序可以怎么做？

**Comment by 12sdj** [comment]
你的意见已收录！
你的建议“加强随机数”已收录，我们将在后续版本中优化这一内容
ID：01

**Comment by caijinyuan123** [comment]
OK


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 12sdj ***@***.***>
发送时间: Thursday, December 29, 2022 5:13:27 PM
收件人: 12sdj/Random-Number-Generator ***@***.***>
抄送: 蔡锦源 ***@***.***>; Author ***@***.***>
主题: Re: [12sdj/Random-Number-Generator] 建议 (Issue #10)


Closed #10<https://github.com/12sdj/Random-Number-Generator/issues/10> as completed.

―
