### ISSUE TITLE
Good news: the official version is coming soon

### ISSUE THREAD

**Issue by Kazie-Yu** [12sdj/Random-Number-Generator#2]
I am happy to write this article on behalf of the entire team. We can tell you that the official version will be released by the next two weeks, with the version number **3.0.0_Release**. In version 3.0.0 we will continue the **Silent (22H2)** philosophy from version 2.x.x. By the way, the beta (early test version) will end soon, so if you want to `continue` testing *Random-Number-Generator*, please move to the Preview version.
我很高兴代表整个团队写这篇文章。我们可以告诉您，正式版本将在下两周前发布，版本号定为**3.0.0_Release**。在3.0.0版本中，我们将继续延续2.x.x版本的Silent(22H2)理念。顺便提一下，测试版本（早期测试版本）将很快结束，若您有意愿继续测试Random-Number-Generator，请移步至Preview版本

**Comment by Kazie-Yu** [comment]
Enjoy it:-)

**Comment by 12sdj** [comment]
That's True

**Comment by 12sdj** [comment]
下周不可能发布正式版本了。请等待23H1(Atonal)版本:-(
这个消息很不好
